/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tapofwar;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author LoganLee
 */
public class panelMain extends javax.swing.JPanel {

    private MainFrame frame;
    private final panelSinglePlayer panelSingle;
    private final panelLocalMulti panelLocalMulti;
    private final panelLANMulti panelLANMulti;
  //  private final panelSetting panelSetting;
    private panelMain panelMain;
    private final GridBagLayout layout;
    /**
     * Creates new form panelMain
     */
    public panelMain(MainFrame frame) {
        initComponents();
        
        this.frame = frame;
        layout = new GridBagLayout();
        
        panelSingle = new panelSinglePlayer(this);
        panelLocalMulti = new panelLocalMulti(this);
        panelLANMulti = new panelLANMulti("127.0.0.1", this);
   //     panelSetting = new panelSetting();
        panelMain = this;
        
        frame.getContentPane().setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        frame.add(panelSingle, c);
        panelSingle.setVisible(false);
        
        c.gridx = 0;
        c.gridy = 0;
        frame.add(panelLocalMulti, c);
        panelLocalMulti.setVisible(false);
        
        c.gridx = 0;
        c.gridy = 0;
        frame.add(panelLANMulti, c);
        panelLANMulti.setVisible(false);
        
        c.gridx = 0;
        c.gridy = 0;
      //  frame.add(panelSetting, c);
    //    panelSetting.setVisible(false);
        
        c.gridx = 0;
        c.gridy = 0;
        frame.add(panelMain, c);
        panelMain.setVisible(true);
        
    }

    public void showMain(){
        panelSingle.setVisible(false);
      //  panelSetting.setVisible(false);
        panelLocalMulti.setVisible(false);
        panelLANMulti.setVisible(false);
        panelMain.setVisible(true);
    }
    
    public void setPanelMain(panelMain panelMain) {
        this.panelMain = panelMain;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        btnSinglePlayer = new javax.swing.JButton();
        btnLocal = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLAN = new javax.swing.JButton();

        setBackground(new java.awt.Color(63, 32, 69));

        lblMain.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        lblMain.setForeground(new java.awt.Color(254, 220, 159));
        lblMain.setText("Tap Of War");

        btnSinglePlayer.setBackground(new java.awt.Color(255, 0, 0));
        btnSinglePlayer.setText("Single Player");
        btnSinglePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinglePlayerActionPerformed(evt);
            }
        });

        btnLocal.setBackground(new java.awt.Color(254, 220, 159));
        btnLocal.setText("Local Multi");
        btnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(254, 220, 159));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLAN.setBackground(new java.awt.Color(254, 220, 159));
        btnLAN.setText("LAN Multi");
        btnLAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSinglePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMain)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblMain)
                .addGap(139, 139, 139)
                .addComponent(btnSinglePlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLAN)
                .addGap(30, 30, 30)
                .addComponent(btnExit)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSinglePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinglePlayerActionPerformed
        panelMain.setVisible(false);
        panelSingle.setVisible(true);
        panelSingle.startGame();
        panelSingle.requestFocusInWindow();
    }//GEN-LAST:event_btnSinglePlayerActionPerformed

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalActionPerformed
        panelMain.setVisible(false);
        panelLocalMulti.setVisible(true);
        panelLocalMulti.startGame();
        panelLocalMulti.requestFocusInWindow();
    }//GEN-LAST:event_btnLocalActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        frame.setVisible(false);
        frame.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLANActionPerformed
        panelMain.setVisible(false);
        panelLANMulti.setVisible(true);
        panelLANMulti.requestFocusInWindow();
        
        new Thread(){
            public void run(){
                panelLANMulti.runServer();
            }
        }.start();
    }//GEN-LAST:event_btnLANActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLAN;
    private javax.swing.JButton btnLocal;
    private javax.swing.JButton btnSinglePlayer;
    private javax.swing.JLabel lblMain;
    // End of variables declaration//GEN-END:variables
}
